(define (problem hanoi-problem) (:domain hanoi-domain)
    (:objects
        tower1 tower2 tower3
        disk1 disk2 disk3 disk4 disk5 
    )
    
    (:init
        (tower tower1)
        (tower tower2)
        (tower tower3)
        (disk disk1)
        (on-disk disk1 disk2)
        (smaller disk1 disk2)
        (smaller disk1 disk3)
        (smaller disk1 disk4)
        (smaller disk1 disk5)
        (disk disk2)
        (on-disk disk2 disk3)
        (smaller disk2 disk3)
        (smaller disk2 disk4)
        (smaller disk2 disk5)
        (disk disk3)
        (on-disk disk3 disk4)
        (smaller disk3 disk4)
        (smaller disk3 disk5)
        (disk disk4)
        (on-disk disk4 disk5)
        (smaller disk4 disk5)
        (disk disk5)
        (on-tower disk5 tower1)
        (not (empty tower1))
        (empty tower2)
        (empty tower3)
        (on-top disk1 tower1)
    )
        
    (:goal (and
        (empty tower1)
        (empty tower2)
        (on-top disk1 tower3)
        (on-disk disk1 disk2)
        (on-disk disk2 disk3)
        (on-disk disk3 disk4)
        (on-disk disk4 disk5)
        (on-tower disk5 tower3)
        )
    )
)